package Model;

import java.math.BigDecimal;
import java.util.Date;

public class Employee {
    private int employeeId;  // This will be auto-generated by DB
    private String username;
    private String name;
    private String email;
    private String password;
    private int branchId;  // Renamed for consistency with database field
    private String address;
    private BigDecimal salary;
    private String phone;
    private String status;
    private Date joiningDate;
    private String position;
    private boolean firstTimeJoined;

    // Constructor to initialize all fields except employeeId, as it's auto-generated
    public Employee(String username, String name, String email, String password, int branchId,
                    String address, BigDecimal salary, String phone, String status, Date joiningDate,
                    String position) {
        this.username = username;
        this.name = name;
        this.email = email;
        this.password = password;
        this.branchId = branchId;
        this.address = address;
        this.salary = salary;
        this.phone = phone;
        this.status = status;
        this.joiningDate = joiningDate;
        this.position = position;
    }

    // Getter and setter for employeeId (set after inserting into DB)
    public int getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    // Getters and setters for other fields
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getBranchId() {
        return branchId;
    }

    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getJoiningDate() {
        return joiningDate;
    }

    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public boolean isFirstTimeJoined() {
        return firstTimeJoined;
    }

    public void setFirstTimeJoined(boolean firstTimeJoined) {
        this.firstTimeJoined = firstTimeJoined;
    }

    // Method to validate login (email and password check)
    public boolean validateLogin(String email, String password) {
        return this.email.equals(email) && this.password.equals(password);
    }

    // Method to display employee details
    public void displayEmployeeInfo() {
        System.out.println("Employee ID: " + employeeId);
        System.out.println("Username: " + username);
        System.out.println("Name: " + name);
        System.out.println("Email: " + email);
        System.out.println("Phone: " + phone);
        System.out.println("Branch ID: " + branchId);
        System.out.println("Address: " + address);
        System.out.println("Salary: " + salary);
        System.out.println("Status: " + status);
        System.out.println("Joining Date: " + joiningDate);
        System.out.println("Position: " + position);
        System.out.println("First Time Joined: " + firstTimeJoined);
    }
}
